version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_build:
      - python -m pip install --upgrade --no-cache-dir pip setuptools wheel
      - python -m pip install --no-cache-dir -r requirements.txt
      - python -m pip install --no-cache-dir .
      - python -m sphinx -b html -d docs/_build/doctrees docs docs/_build/html

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
