version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    install:
      - pip install tox
    build:
      html:
        - tox -e docs
        - mkdir -p ${READTHEDOCS_OUTPUT}/html
        - cp -r docs/_build/html/* ${READTHEDOCS_OUTPUT}/html/

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
